#!/usr/bin/env bash
#
# Install pm script
#
destination="${1:-${HOME}/.local/bin}"

source="$(pwd)"

if [[ -f "${destination}/pm" ]]; then
    echo "there is already a link in ${destination}"
    exit 1
fi

if [[ ! -d "${source}" ]]; then
    echo "source directory ${source} does not exist"
    exit 1
fi

if [[ ! -f "${source}/pm" ]]; then
    echo "script 'pm' not found in ${source}"
    exit 1
fi

command ln -s "${source}/pm" "${destination}/pm"
echo "link created in ${destination}"
