#!/usr/bin/env bash
#
# Uninstall pm script
#
destination="${1:-${HOME}/.local/bin}"

if [[ -f "${destination}/pm" ]]; then
    command rm "${destination}/pm"

    echo "link removed from ${destination}"
else
    echo "no link found in ${destination}"
    exit 1
fi
